// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: targets.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DestroyerClient is the client API for Destroyer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DestroyerClient interface {
	// RPC method that acquires targets
	AcquireTargets(ctx context.Context, in *TargetsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// RPC method that lists targets acquired from the database
	ListTargets(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TargetsResponse, error)
}

type destroyerClient struct {
	cc grpc.ClientConnInterface
}

func NewDestroyerClient(cc grpc.ClientConnInterface) DestroyerClient {
	return &destroyerClient{cc}
}

func (c *destroyerClient) AcquireTargets(ctx context.Context, in *TargetsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/destroyer.Destroyer/AcquireTargets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *destroyerClient) ListTargets(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TargetsResponse, error) {
	out := new(TargetsResponse)
	err := c.cc.Invoke(ctx, "/destroyer.Destroyer/ListTargets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DestroyerServer is the server API for Destroyer service.
// All implementations must embed UnimplementedDestroyerServer
// for forward compatibility
type DestroyerServer interface {
	// RPC method that acquires targets
	AcquireTargets(context.Context, *TargetsRequest) (*emptypb.Empty, error)
	// RPC method that lists targets acquired from the database
	ListTargets(context.Context, *emptypb.Empty) (*TargetsResponse, error)
	mustEmbedUnimplementedDestroyerServer()
}

// UnimplementedDestroyerServer must be embedded to have forward compatible implementations.
type UnimplementedDestroyerServer struct {
}

func (UnimplementedDestroyerServer) AcquireTargets(context.Context, *TargetsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcquireTargets not implemented")
}
func (UnimplementedDestroyerServer) ListTargets(context.Context, *emptypb.Empty) (*TargetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTargets not implemented")
}
func (UnimplementedDestroyerServer) mustEmbedUnimplementedDestroyerServer() {}

// UnsafeDestroyerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DestroyerServer will
// result in compilation errors.
type UnsafeDestroyerServer interface {
	mustEmbedUnimplementedDestroyerServer()
}

func RegisterDestroyerServer(s grpc.ServiceRegistrar, srv DestroyerServer) {
	s.RegisterService(&Destroyer_ServiceDesc, srv)
}

func _Destroyer_AcquireTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DestroyerServer).AcquireTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/destroyer.Destroyer/AcquireTargets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DestroyerServer).AcquireTargets(ctx, req.(*TargetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Destroyer_ListTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DestroyerServer).ListTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/destroyer.Destroyer/ListTargets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DestroyerServer).ListTargets(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Destroyer_ServiceDesc is the grpc.ServiceDesc for Destroyer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Destroyer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "destroyer.Destroyer",
	HandlerType: (*DestroyerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcquireTargets",
			Handler:    _Destroyer_AcquireTargets_Handler,
		},
		{
			MethodName: "ListTargets",
			Handler:    _Destroyer_ListTargets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "targets.proto",
}
